version: "3"
services:
    notebook:
        build: jupyter
        image: notebook
        ports:
            - "8888:8888"
            - "10000:10000"
        volumes:
            - "./data/notebook:/home/jovyan:rw"
            - "./data/mlflow-artifact:/data/mlflow-artifact:rw"
        environment:
            JUPYTER_ENABLE_LAB: "true"
        depends_on:
        - "mlflow"
    mysql:
        image: mysql:5.7
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - "./data/mysql:/var/lib/mysql:rw"
    mlflow:
        build: mlflow
        image: mlflow
        env_file:
            - .env
        ports:
            - "80:80"
        depends_on:
            - "mysql"
        volumes:
            - "./data/mlflow-artifact:/data/mlflow-artifact:rw"
        command: 
            - mlflow
            - server
            - --host
            - "0.0.0.0"
            - -p
            - "80"
            - --default-artifact-root
            - /data/mlflow-artifact
            - --backend-store-uri
            - mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
        restart: on-failure
